### ISSUE TITLE
The requirements for reflection in mySQL package

### ISSUE THREAD

**Issue by HenilMistry** [harshil-padasala/pymachine#2]
The requirements are mentioned below, try to make objects like that. The website to see sample objects in proper formate.
- `https://jsonformatter.curiousconcept.com/#`

## Antivirus Requirements
- The sample object
  - `{
   "Antivirus name":{
      "version":"",
      "enabled":"",
      "is_up_to_date":""
   }
}`
![image](https://user-images.githubusercontent.com/77051908/189910014-c1dbc4d2-bb37-4fbe-9d41-26f0a0be8ff0.png)

## System information
- The sample object
  - `"system":{
		"node" : "",
		"processor" : "",
		"os_name" : "",
		"os_version": "",
		"system_type" : ""	
	}`

## Network Information
- The sample object
  - `"network_wireless":{
		"IPv4" : "",
		"Subnet" : "",
		"Gateway" : "",
		"DHCP" : "",
		"DNS" : "",
		"Pyhsical" : "" 
	}`

## Final JSON object look
![image](https://user-images.githubusercontent.com/77051908/189912674-d6bbc226-cc1a-4bea-8beb-e3d49301902d.png)

**Comment by harshil-padasala** [comment]
Done, Implemented
